{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wbs-platform.fullname" . }}-api
  labels:
    {{- include "wbs-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "wbs-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
{{- if .Values.portal.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wbs-platform.fullname" . }}-portal
  labels:
    {{- include "wbs-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal
spec:
  minAvailable: {{ .Values.portal.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "wbs-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: portal
{{- end }}
