{{- $createPostgresSecret := and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) -}}
{{- $createExternalSecret := and (not .Values.postgresql.enabled) (not .Values.externalPostgresql.existingSecret) -}}
{{- if or $createPostgresSecret $createExternalSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wbs-platform.databaseSecretName" . }}
  labels:
    {{- include "wbs-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ ternary .Values.postgresql.auth.username .Values.externalPostgresql.username .Values.postgresql.enabled | quote }}
  password: {{ ternary .Values.postgresql.auth.password .Values.externalPostgresql.password .Values.postgresql.enabled | quote }}
  database: {{ ternary .Values.postgresql.auth.database .Values.externalPostgresql.database .Values.postgresql.enabled | quote }}
{{- end }}
